// <auto-generated />
using CodexEx1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CodexEx1.Migrations
{
    [DbContext(typeof(WooSahContext))]
    partial class WooSahContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodexEx1.Models.WooSahPOCOModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Etching");

                    b.Property<string>("Finish");

                    b.Property<string>("Material");

                    b.Property<string>("Model");

                    b.HasKey("ID");

                    b.ToTable("WooSahPOCOModel");
                });
#pragma warning restore 612, 618
        }
    }
}
