//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooSahCodex.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WooSah
    {
        public long WooSahId { get; set; }
        public string Model { get; set; }
        public string Etching { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
        public string Finish { get; set; }
        public bool IsValid { get; set; }
    }
}
